env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - standard-with-typescript
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: './tsconfig.json'
plugins:
  - react
  - import
  - unused-imports
rules:
  react/react-in-jsx-scope: off
  react/prop-types: off
  semi:
    - error
    - never
  import/order:
    - error
    - {
        groups:
          ['builtin', 'external', 'internal', ['parent', 'sibling', 'index']],
        'newlines-between': 'always'
      }
  unused-imports/no-unused-imports: error
  unused-imports/no-unused-vars: error
